[package]
authors = [
    "Ulf Lilleengen <lulf@redhat.com>",
    "Bob McWhirter <bmcwhirt@redhat.com>"

]
edition = "2018"
name = "blinky"
version = "0.1.0"

[workspace]

[dependencies]
defmt = "0.2"
defmt-rtt = "0.2"
panic-probe = { version = "0.2.0", features = ["print-defmt"] }
drogue-device = { path = "../../../../device", features = ["defmt", "defmt-info"], default-features = false }
atomic-polyfill = { version = "0.1.1" }
embedded-hal = { version = "0.2.4", features = ["unproven"] }

rp2040-pac2 = { git = "https://github.com/Dirbaio/rp2040-pac", rev="254f4677937801155ca3cb17c7bb9d38eb62683e" }
cortex-m-rt = "0.7"
cortex-m = { version = "0.7", features = ["inline-asm"] }

# TODO: Get rid of these embassy deps some day
embassy = {git = "https://github.com/embassy-rs/embassy.git", rev = "548593ea415c79472bd2cf2d0c59aadfcf5f715c", default-features = false}
embassy-rp = {git = "https://github.com/embassy-rs/embassy.git", rev = "548593ea415c79472bd2cf2d0c59aadfcf5f715c", default-features = false}

# embassy = {path = "../../../../../../embassy/embassy", default-features = false}
# embassy-rp = {path = "../../../../../../embassy/embassy-rp", default-features = false}

[features]
default = [
    "defmt-default",
]
defmt-default = []
defmt-trace = [ ]
defmt-debug = [ ]
defmt-info = [ ]
defmt-warn = [ ]
defmt-error = [ ]
