[package]
authors = [
    "Ulf Lilleengen <lulf@redhat.com>",
    "Bob McWhirter <bmcwhirt@redhat.com>"
]
edition = "2018"
name = "lora-discovery"
version = "0.1.0"
resolver = "2"
description = "STM32 LoRaWAN Discovery board sending data to The Things Network"
keywords = ["lorawan", "lora", "stm32l0", "networking", "iot"]

[workspace]

[dependencies]
log = "0.4"
rtt-logger = "0.1"
rtt-target = { version = "0.2.0", features = ["cortex-m"] }
embedded-hal = { version = "0.2.4", features = ["unproven"] }
panic-probe = { version = "0.2.0", features = ["print-rtt"] }

drogue-device = { path = "../../../device", features = ["log", "lora+sx127x"], default-features = false }
cortex-m-rt = "0.7"
cortex-m = { version = "0.7", features = ["inline-asm"] }
heapless = "0.6"
void = { version = "1", default-features = false }
rand_core = { version = "0.6", default-features = false }

embassy = {git = "https://github.com/embassy-rs/embassy.git", rev = "548593ea415c79472bd2cf2d0c59aadfcf5f715c", default-features = false, features = ["time-tick-32768hz"] }
embassy-stm32 = {git = "https://github.com/embassy-rs/embassy.git", rev = "548593ea415c79472bd2cf2d0c59aadfcf5f715c", default-features = false, features = ["stm32l072cz", "time-driver-tim2"] }

#embassy = {path = "../../../../../embassy/embassy", default-features = false}
#embassy-stm32 = {path = "../../../../../embassy/embassy-stm32", default-features = false, features = ["stm32l072cz"] }

[profile.release]
codegen-units = 1
debug = 2
opt-level = "s"
lto = "fat"
debug-assertions = false
incremental = false
overflow-checks = false
