[package]
authors = [
    "Ulf Lilleengen <lulf@redhat.com>",
    "Bob McWhirter <bmcwhirt@redhat.com>"
]
edition = "2018"
name = "nucleo-h743zi_blinky"
version = "0.1.0"
resolver = "2"
description = "STM32 Nucleo-H743 blinky"
keywords = ["basic", "blinky", "stm32", "stm32h7"]

[workspace]

[features]
default = [
    "defmt-default",
]
defmt-default = []
defmt-trace = []
defmt-debug = []
defmt-info = []
defmt-warn = []
defmt-error = []

[dependencies]
defmt = "0.2"
defmt-rtt = "0.2"
panic-probe = { version = "0.2.0", features = ["print-defmt"] }

embedded-hal = { version = "0.2.4", features = ["unproven"] }
drogue-device = { path = "../../../../device", features = ["wifi+esp8266", "defmt", "defmt-trace"], default-features = false }
cortex-m-rt = "0.7"
cortex-m = { version = "0.7", features = ["inline-asm"] }
heapless = "0.6"
void = { version = "1", default-features = false }

embassy = {git = "https://github.com/embassy-rs/embassy.git", rev = "548593ea415c79472bd2cf2d0c59aadfcf5f715c", default-features = false, features = ["defmt", "defmt-info", "time", "time-tick-32768hz"]}
embassy-stm32 = {git = "https://github.com/embassy-rs/embassy.git", rev = "548593ea415c79472bd2cf2d0c59aadfcf5f715c", default-features = false, features = ["stm32h743zi", "defmt", "defmt-info", "memory-x", "time-driver-tim2"] }

[profile.release]
debug = 2
opt-level = "s"
lto = "fat"
