[package]
authors = [
    "Ulf Lilleengen <lulf@redhat.com>",
    "Bob McWhirter <bmcwhirt@redhat.com>"
]
edition = "2018"
name = "drogue-device"
version = "0.1.0"

[lib]
doctest = false

[dependencies]
embassy = {git = "https://github.com/embassy-rs/embassy.git", rev = "548593ea415c79472bd2cf2d0c59aadfcf5f715c", default-features = false, features = ["executor-agnostic"] }
#embassy = {default-features = false, path = "../../../embassy/embassy", features = ["defmt"]}

# LoRa dependencies
lorawan-device = { git = "https://github.com/lulf/rust-lorawan.git", rev = "2279fe55e9aeda5d3b9d2593763e3b2c031fa695", default-features = false, optional = true }
lorawan-encoding = { git = "https://github.com/lulf/rust-lorawan.git", rev = "2279fe55e9aeda5d3b9d2593763e3b2c031fa695", default-features = false, features = ["default-crypto"], optional = true }
#lorawan-device = { path = "../../../rust-lorawan/device", default-features = false, optional = true }
#lorawan-encoding = { path = "../../../rust-lorawan/encoding", default-features = false, features = ["default-crypto"], optional = true }
bit_field = { version = "0.10", optional = true }

# Wifi Dependencies
nom = { version = "6.1.2", default-features = false, optional = true }
moveslice = { version = "2.0", optional = true }

# TLS dependency
drogue-tls = { git = "https://github.com/drogue-iot/drogue-tls.git", rev = "59cb23017f546da8e0f186042758226165400548", default-features = false, features = ["async"], optional = true}
#drogue-tls = { version = "0.2.0", default-features = false, features = ["async"], optional = true}
#drogue-tls = {path = "../../drogue-tls", default-features = false, features = ["async"], optional = true}
rand_core = { version = "0.6.2", default-features = false, optional = true }

# Utilities
futures = { version = "0.3", default-features = false }
heapless = "0.6"
embedded-hal = { version = "0.2.4", features = ["unproven"] }
atomic-polyfill = "0.1"
generic-array = "0.14"
critical-section = "0.2.1"

# Logging alternatives
log = { version = "0.4", optional = true }
defmt = { version = "0.2", optional = true }

# HTTP dependencies
base64 = { version = "0.13.0", default-features = false }

[dev-dependencies]
embassy-std = {git = "https://github.com/embassy-rs/embassy.git", rev = "548593ea415c79472bd2cf2d0c59aadfcf5f715c", default-features = false }
#embassy-std = {default-features = false, path = "../../../embassy/embassy-std" }

drogue-device-macros = { path = "../macros" }
futures = { version = "0.3", default-features = false, features = ["executor"] }
arrayvec = { version = "0.6" }
env_logger = "0.8"

[features]
default = [ "std", "log", "time" ]
std = ["embassy/std"]
time = ["embassy/time"]
"lora+sx127x" = ["lorawan-device", "lorawan-encoding", "bit_field"]
"lora+rak811" = ["nom", "moveslice"]
"wifi+esp8266" = ["nom", "moveslice"]
lora = []
wifi = []
fonts = []
tls = ["drogue-tls", "rand_core"]

defmt-default = [ ]
defmt-trace = [ ]
defmt-debug = [ ]
defmt-info = [ ]
defmt-warn = [ ]
defmt-error = [ ]
